### ISSUE TITLE
Add missing fcport in configFile/loadFile for a2lt-1-0-0-op-fc-bm-005

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/Accessport2LtpTranslator#78]
Forwarding:
```
  - forwarding-name: BasicAuthRequestCausesInquiryForAuthentication
    uuid: a2lt-1-0-0-op-fc-bm-005
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/inquire-basic-auth-approvals
          uuid: a2lt-1-0-0-op-s-bm-012
        - server-name: /v1/inquire-oam-request-approvals
          uuid: a2lt-1-0-0-op-s-bm-005
      fc-port-update:
        - server-name: /v1/inquire-basic-auth-approvals
          uuid: a2lt-1-0-0-op-s-bm-012
        - server-name: /v1/inquire-oam-request-approvals
          uuid: a2lt-1-0-0-op-s-bm-005
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      # [all oam requests]
    consequent-requests:
      - client-name: AdministratorAdministration://v1/approve-oam-request
        uuid: a2lt-1-0-0-op-c-bs-aa-2-1-0-000
```

fc-port for  a2lt-1-0-0-op-s-bm-005 is missing; add in configFile/loadFile:
![image](https://github.com/openBackhaul/Accessport2LtpTranslator/assets/57349523/cd58f6a5-c23b-4b2c-b06d-4b3974f373ec)

snippet for configFile:
```
              {
                "local-id": "001",
                "port-direction": "core-model-1-4:PORT_DIRECTION_TYPE_MANAGEMENT",
                "logical-termination-point": "a2lt-1-0-0-op-s-bm-005"
              },
```

(When adding to loadFile ensure that identations of snippet are adjusted.)
